### ISSUE TITLE
Glide Cannot draw recycled bitmaps

### ISSUE THREAD

**Issue by Tooroop** [MikeOrtiz/TouchImageView#162]
Hi, I'm seeing in my Crashlytics crashes regarding TouchImageView and Glide. I can't reproduce this error on any of my devices. It says:
Fatal Exception: java.lang.IllegalArgumentException: Cannot draw recycled bitmaps.

Do you have any idea if it is a bug in TouchImageView or maybe I am not using Glide as I should.
This is how I load the image:
```java
Glide.with(getActivity()).load(imageUrl).into(mainImageTarget);
```

```java
private SimpleTarget<GlideDrawable> mainImageTarget = new SimpleTarget<GlideDrawable>() {
        @Override
        public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
            if(progressBar != null && mImageView != null) {
                progressBar.setVisibility(View.GONE);
                mImageView.setImageDrawable(resource);
                mImageView.setZoom(1f);
            }
        }
    };
```

In onStop I have:

```java
if(mainImageTarget != null) {
    Glide.clear(mainImageTarget);
 }
```

Here is the full stacktracek of the error:
```
Fatal Exception: java.lang.IllegalArgumentException: Cannot draw recycled bitmaps
       at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:789)
       at android.view.GLES20RecordingCanvas.drawBitmap(GLES20RecordingCanvas.java:118)
       at com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable.draw(GlideBitmapDrawable.java:101)
       at android.widget.ImageView.onDraw(ImageView.java:1008)
       at com.airgoat.goat.view.TouchImageView.onDraw(TouchImageView.java:286)
       at android.view.View.draw(View.java:14600)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.View.getDisplayList(View.java:13579)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3137)
       at android.view.View.getDisplayList(View.java:13472)
       at android.view.View.getDisplayList(View.java:13579)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
       at android.view.View.getDisplayList(View.java:13533)
       at android.view.View.getDisplayList(View.java:13579)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
       at android.view.View.draw(View.java:14603)
       at android.support.v4.view.ViewPager.draw(ViewPager.java:2447)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.View.getDisplayList(View.java:13579)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
       at android.view.View.draw(View.java:14603)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.View.getDisplayList(View.java:13579)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
       at android.view.View.getDisplayList(View.java:13533)
       at android.view.View.getDisplayList(View.java:13579)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
       at android.view.View.getDisplayList(View.java:13533)
       at android.view.View.getDisplayList(View.java:13579)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
       at android.view.View.getDisplayList(View.java:13533)
       at android.view.View.getDisplayList(View.java:13579)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
       at android.view.View.draw(View.java:14603)
       at android.widget.FrameLayout.draw(FrameLayout.java:467)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2579)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.View.getDisplayList(View.java:13579)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1198)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2506)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2372)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2175)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1237)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5181)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:561)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

I am suspecting that it is a TouchImageView error since it is referenced in the stacktrace:
` at com.airgoat.goat.view.TouchImageView.onDraw(TouchImageView.java:286)`

**Comment by hannesa2** [comment]
Is it still present in most recent version ?
If yes, please reopen it, and a running example would be fine

**Comment by huunhan18pro** [comment]
The library is great. But I got this issue with Glide. 

![Screen Shot 2021-07-22 at 10 32 27 AM](https://user-images.githubusercontent.com/5953762/126586668-fb21533f-b831-499a-9964-4cbf91999d75.png)
`Glide.with(context).load(url).into(new CustomTarget<Drawable>() {
                    @Override
                    public void onResourceReady(@NonNull Drawable resource, @Nullable Transition<? super Drawable> transition) {
                        if (progressBar != null) {
                            progressBar.setVisibility(View.GONE);
                        }
                        view.setImageDrawable(resource);

                        if (isCenterCrop)
                            view.setScaleType(ImageView.ScaleType.CENTER_CROP);
                    }

                    @Override
                    public void onLoadCleared(@Nullable Drawable placeholder) {
                        if (progressBar != null) {
                            progressBar.setVisibility(View.GONE);
                        }
                    }
                });`
