### ISSUE TITLE
Error: IllegalArgumentException 

### ISSUE THREAD

**Issue by rahulsahni06** [MikeOrtiz/TouchImageView#301]
Using v3.0.1

```
 <com.ortiz.touchview.TouchImageView
        android:id="@+id/imageView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginBottom="16dp"
        app:layout_constraintBottom_toTopOf="@+id/view"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/appBar"
        tools:srcCompat="@tools:sample/avatars" />
```

```
Glide.with(this)
            .load(file)
            .signature(ObjectKey(file.lastModified()))
            .into(imageView)
```

Facing this error in production app
Stack trace:
```
Fatal Exception: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.o.c.f.b, parameter e1
       at com.ortiz.touchview.TouchImageView$GestureListener.onFling(TouchImageView.java:842)
       at android.view.GestureDetector.onTouchEvent(GestureDetector.java:656)
       at com.ortiz.touchview.TouchImageView$PrivateOnTouchListener.onTouch(TouchImageView.java:893)
       at android.view.View.dispatchTouchEvent(View.java:12534)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:444)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3466)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:402)
       at android.view.View.dispatchPointerEvent(View.java:12779)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5286)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5086)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4601)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4654)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4620)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4760)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4628)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4817)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4601)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4654)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4620)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4628)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4601)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7329)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7298)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7259)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7435)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:247)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:165)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by hannesa2** [comment]
It was fixed with `3.0.2`, I recommend to use `3.0.3`
