### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by rhasanr** [MikeOrtiz/TouchImageView#309]
I got this crash from firebase crash analytics. Don't know the generation scenario. Can you please look into it.

Fatal Exception: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.ortiz.touchview.TouchImageView$e.onFling, parameter e1
       at com.ortiz.touchview.TouchImageView.access$getFling$p(TouchImageView.java:27)
       at com.ortiz.touchview.TouchImageView$GestureListener.onFling(TouchImageView.java:837)
       at android.view.GestureDetector.onTouchEvent(GestureDetector.java:782)
       at com.ortiz.touchview.TouchImageView$PrivateOnTouchListener.onTouch(TouchImageView.java:893)
       at android.view.View.dispatchTouchEvent(View.java:14372)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:727)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1922)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4051)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:685)
       at android.view.View.dispatchPointerEvent(View.java:14644)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6522)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6309)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5747)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5800)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5766)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5922)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5774)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5979)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5747)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5800)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5766)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5774)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5747)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8906)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8767)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8720)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9042)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:197)
       at android.app.ActivityThread.main(ActivityThread.java:7857)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by hannesa2** [comment]
It should be solved with latest version `3.0.3` https://github.com/MikeOrtiz/TouchImageView/pull/264
